twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        '%kernel.project_dir%/bundle/TWD/HelloWorldBundle/templates': TWDHelloWorldBundle

when@test:
    twig:
        strict_variables: true
